import Participant from "./Participant"
import Project from "./Project"
import Event from "./Event"
import Venue from "./Venue"
import FieldNote from "./FieldNote"
import ContentEditor from "./ContentEditor"
import Page from "./Page"
import Press from "./Press"
import PressRelease from "./PressRelease"
import PressCoverage from "./PressCoverage"
import About from "./About"
import Team from "./Team"
import Contact from "./Contact"

export const schemaTypes = [About, Team, Contact, Page, Participant, Project, Event, Venue, FieldNote, Press, PressRelease, PressCoverage, ContentEditor]
